### ISSUE TITLE
Issues: Unable to change account email.

### ISSUE THREAD

**Issue by StryderGX** [CrouchJumpInc/fangagement-public#15]
Clicking change email on account does nothing.

**Comment by StryderGX** [comment]
Update - 3.9.22

Now that I'm on the correct app. 

One of the only issue I have fund thus far is not being able to change my email. When pressing change on email it nothing happens.

The second issue being notifications are not clearing. 2 random notifications are blue about half way down the notification list are blue and won't clear so I have 2 notifications always.

But far less to worry about than when I wasn't running the proper app. <3

**Comment by DrVonDevious** [comment]
This is in the form however the task for it is in post alpha. I will disable the button for now
