### ISSUE TITLE
Can't access app after registering and/or signing in

### ISSUE THREAD

**Issue by ILikeConcerts** [CrouchJumpInc/fangagement-public#16]
I tried to log into my already created fan account, which loaded the timeline briefly then changed immediately to a CJ splash page. 

I figured my account must had been deleted so I registered with my already existing account information, to which put me immediately back to the splash page.

I then attempted Multiple logins which all resulted the same.

I then chose to register a new account with a new name and email all together, an account named FerretPenis to try and challenge the profanity filter,

And still resulted in the splash page 

![Screenshot_20220306-162713](https://user-images.githubusercontent.com/101068375/156943620-4d135fc7-f3d7-4fad-b882-f7a96e7ec5f3.jpg)

Mobile Device: One Plus 6
OS: OxygenOS ver. 11.1.2.2

**Comment by placidowang** [comment]
I also got the CJ logo splash screen after logging in to an existing account, and also when signing up as a user with profanity in my username

**Comment by DrVonDevious** [comment]
@placidowang @ILikeConcerts try this one more time. I may have fixed it
