### ISSUE TITLE
ISSUE: As a fan I should be able to add/update my Profile Picture

### ISSUE THREAD

**Issue by moorej2017** [CrouchJumpInc/fangagement-public#2]
pfp not updating.

**Comment by DrVonDevious** [comment]
@moorej2017 @hjames82 just pushed a fix for this let me know if it persists

**Comment by moorej2017** [comment]
@DrVonDevious still not working for me, but I’m seeing other people’s profile pictures pop up

**Comment by hjames82** [comment]
@DrVonDevious same as Jimmy after your push, I was not able to add my own but I could see yours and @ankrudov
