### ISSUE TITLE
Logged into one account with the email and login information of another account. 

### ISSUE THREAD

**Issue by ILikeConcerts** [CrouchJumpInc/fangagement-public#21]
I logged out of the test account "FerretPenis", logged out, and entered my "Concerts" account and it logged me back into "FerretPenis". Logged out and fully reloaded the expo app and was not able to recreate the issue. I don't know if fluke or not but just thought I'd include it in case.

**Comment by DrVonDevious** [comment]
Hopefully, this is addressed in the next update. Once we update try to replicate this again

**Comment by ILikeConcerts** [comment]
ok will do after the next update
