### ISSUE TITLE
ISSUE: As a fan I should be able to change my Email Address? *

### ISSUE THREAD

**Issue by ILikeConcerts** [CrouchJumpInc/fangagement-public#24]
For all the multiple accounts, they all have *"Your Email"* in the profile settings section where my email is supposed to be shown. the *"Change"* button is clicked on, it shows that I register my touch but doesn't change anything or allow me to input any email.

**Comment by hjames82** [comment]
Eric, this is a known bug because the feature is not complete.
We are waiting on an update from the dev team to re-test.
