### ISSUE TITLE
Register an account as a fan?

### ISSUE THREAD

**Issue by hjames82** [CrouchJumpInc/fangagement-public#9]
I first created a new fan account: 
user: cjjames
email: james@crouchjump.com

I then clicked the settings menu and it logged me out
I then created a new account:
user: fuckdick
email: fuckdick@gmail.com

It didn't say it didn't create the account, it just logged me in after submission, no errors or warnings. But when I went to post to see if it had created it or not, the user that was displayed is cjjames

Seems like a user session issue.

**Comment by DrVonDevious** [comment]
Created a card for this FANS-129 and linking another issue #17
